graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["archlette-demo - gateway - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 29 ["gateway"]
      style 29 fill:#ffffff,stroke:#ac5b15,color:#ac5b15

      39("<div style='font-weight: bold'>main.getServiceUrl</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div>")
      style 39 fill:#85bbf0,stroke:#5d82a8,color:#000000
      40("<div style='font-weight: bold'>main.callService</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div>")
      style 40 fill:#85bbf0,stroke:#5d82a8,color:#000000
    end

  end