graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["archlette-demo - flarelette-demo-ui - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 5 ["flarelette-demo-ui"]
      style 5 fill:#ffffff,stroke:#ac5b15,color:#ac5b15

      10("<div style='font-weight: bold'>layouts.BaseLayout</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Server-side render function<br />for BaseLayout. Generates<br />HTML output from Astro<br />component template and props.</div>")
      style 10 fill:#85bbf0,stroke:#5d82a8,color:#000000
      11("<div style='font-weight: bold'>layouts.Props</div><div style='font-size: 70%; margin-top: 0px'>[Component: interface]</div>")
      style 11 fill:#85bbf0,stroke:#5d82a8,color:#000000
    end

  end