graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["archlette-demo - gateway - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 29 ["gateway"]
      style 29 fill:#ffffff,stroke:#ac5b15,color:#ac5b15

      30("<div style='font-weight: bold'>auth</div><div style='font-size: 70%; margin-top: 0px'>[Component: module]</div><div style='font-size: 80%; margin-top:10px'>Authentication and token<br />minting</div>")
      style 30 fill:#85bbf0,stroke:#5d82a8,color:#000000
      31("<div style='font-weight: bold'>env</div><div style='font-size: 70%; margin-top: 0px'>[Component: module]</div><div style='font-size: 80%; margin-top:10px'>Environment bindings for<br />Gateway Worker</div>")
      style 31 fill:#85bbf0,stroke:#5d82a8,color:#000000
      32("<div style='font-weight: bold'>main</div><div style='font-size: 70%; margin-top: 0px'>[Component: module]</div><div style='font-size: 80%; margin-top:10px'>Flarelette Gateway Entry<br />point for all API traffic.<br />Routes requests to<br />microservices with internal<br />JWT authentication (EdDSA<br />signed). All input is<br />validated with Zod - zero<br />trust!</div>")
      style 32 fill:#85bbf0,stroke:#5d82a8,color:#000000
      33("<div style='font-weight: bold'>validation</div><div style='font-size: 70%; margin-top: 0px'>[Component: module]</div><div style='font-size: 80%; margin-top:10px'>Input validation schemas<br />using Zod All input is<br />validated - zero trust!</div>")
      style 33 fill:#85bbf0,stroke:#5d82a8,color:#000000
    end

    32-- "<div>imports Env</div><div style='font-size: 70%'></div>" -->31
    32-- "<div>imports<br />getOrMintInternalToken</div><div style='font-size: 70%'></div>" -->30
  end