graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["archlette-demo - flarelette-demo-ui - Components"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 5 ["flarelette-demo-ui"]
      style 5 fill:#ffffff,stroke:#ac5b15,color:#ac5b15

      12("<div style='font-weight: bold'>pages.contact</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Server-side render function<br />for contact. Generates HTML<br />output from Astro component<br />template and props.</div>")
      style 12 fill:#85bbf0,stroke:#5d82a8,color:#000000
      13("<div style='font-weight: bold'>pages.formatDate</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div>")
      style 13 fill:#85bbf0,stroke:#5d82a8,color:#000000
      14("<div style='font-weight: bold'>pages.events</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Server-side render function<br />for events. Generates HTML<br />output from Astro component<br />template and props.</div>")
      style 14 fill:#85bbf0,stroke:#5d82a8,color:#000000
      15("<div style='font-weight: bold'>pages.index</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Server-side render function<br />for index. Generates HTML<br />output from Astro component<br />template and props.</div>")
      style 15 fill:#85bbf0,stroke:#5d82a8,color:#000000
      16("<div style='font-weight: bold'>pages.news</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Server-side render function<br />for news. Generates HTML<br />output from Astro component<br />template and props.</div>")
      style 16 fill:#85bbf0,stroke:#5d82a8,color:#000000
      17("<div style='font-weight: bold'>pages.roster</div><div style='font-size: 70%; margin-top: 0px'>[Component: function]</div><div style='font-size: 80%; margin-top:10px'>Server-side render function<br />for roster. Generates HTML<br />output from Astro component<br />template and props.</div>")
      style 17 fill:#85bbf0,stroke:#5d82a8,color:#000000
    end

  end