@startuml
set separator none
title archlette-demo - gateway - Components

top to bottom direction
skinparam ranksep 60
skinparam nodesep 30

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
  defaultFontName "Arial"
}

hide stereotype

skinparam rectangle<<archlettedemo.gateway.maincallService>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<archlettedemo.gateway.maingetServiceUrl>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<archlettedemo.gateway>> {
  BorderColor #ac5b15
  FontColor #ac5b15
  shadowing false
}

rectangle "gateway\n<size:10>[Container: Cloudflare Worker]</size>" <<archlettedemo.gateway>> {
  rectangle "==main.getServiceUrl\n<size:10>[Component: function]</size>" <<archlettedemo.gateway.maingetServiceUrl>> as archlettedemo.gateway.maingetServiceUrl
  rectangle "==main.callService\n<size:10>[Component: function]</size>" <<archlettedemo.gateway.maincallService>> as archlettedemo.gateway.maincallService
}

@enduml