@startuml
set separator none
title archlette-demo - image-service - Components

top to bottom direction
skinparam ranksep 60
skinparam nodesep 30

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
  defaultFontName "Arial"
}

hide stereotype

skinparam rectangle<<archlettedemo.imageservice.main>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<archlettedemo.imageservice>> {
  BorderColor #ac5b15
  FontColor #ac5b15
  shadowing false
}

rectangle "image-service\n<size:10>[Container: Cloudflare Worker]</size>" <<archlettedemo.imageservice>> {
  rectangle "==main\n<size:10>[Component: module]</size>\n\nImage Service Manages image uploads and galleries using R2 storage. All endpoints require internal JWT verification." <<archlettedemo.imageservice.main>> as archlettedemo.imageservice.main
}

@enduml